package com.carbo.fleet.model;

public enum Role {
    ROLE_ADMIN, ROLE_USER, ROLE_CARBO_ADMIN, ROLE_BACK_OFFICE, ROLE_APP, ROLE_READ_ONLY, ROLE_OPERATION,ROLE_SERVICEMANAGER,
    ROLE_MS_ORGANIZATION, ROLE_MS_ADMIN, ROLE_MS_WELL, ROLE_MS_PAD, ROLE_MS_OPERATOR, ROLE_MS_DISTRICT, ROLE_MS_FLEET, ROLE_MS_VENDOR, ROLE_MS_EMAIL,
    ROLE_MS_MISC_DATA, ROLE_MS_JOB, ROLE_MS_PUMP_ISSUE, ROLE_MS_ACTIVITY_LOG, ROLE_MS_FIELD_TICKET, ROLE_MS_ONSITE_EQUIPMENT, ROLE_MS_CHANGE_LOG,
    ROLE_MS_PROPPANT_DELIVERY, ROLE_MS_CHEMICAL_DELIVERY, ROLE_MS_PROPPANT_STAGE, ROLE_MS_CHEMICAL_STAGE, ROLE_MS_WS, ROLE_MS_PUMP_SCHEDULE,
    ROLE_MS_WELL_INFO, ROLE_MS_CHECKLIST, ROLE_MS_WORKOVER, ROLE_MS_MAINTENANCE, ROLE_MS_CONSUMABLE, ROLE_MS_OPERATION_OVERVIEW, ROLE_MS_SERVICE_COMPANY,
    ROLE_MS_IRON_FAILURE, ROLE_MS_COST, ROLE_MS_CASING, ROLE_MOVE_ONSITE_EQUIPMENT, ROLE_SALES_USER, ROLE_USER_MANAGEMENT, ROLE_PRICEBOOK, ROLE_PROCUREMENT, ROLE_FIELDCOORDINATOR,
    ROLE_SUPER_SALES_USER, ROLE_CREW_SCHEDULING, ROLE_DISCOUNT, ROLE_SAFETY, ROLE_LEAD_OWNER, ROLE_LEAD_MANAGER
}
