spring:
  cloud:
    stream:
      bindings:
        output:
          destination:  orgChangeTopic
          content-type: application/json
      kafka:
        binder:
          zkNodes: localhost:2181
          brokers: localhost:9092
  data:
    mongodb:
      uri: "mongodb://carbo:carbor0x!@52.171.54.61:27017/?directConnection=true&authSource=admin"
      database: FracProOps
server:
  port: 8089
  shutdown: graceful

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8901/auth/user

eureka:
  instance:
    preferIpAddress: true
  client:
    enabled: false
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#Setting the logging levels for the service
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.carbo: DEBUG